# Generated by Django 3.1 on 2022-06-18 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_category', models.FloatField()),
                ('to_category', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-username'],
            },
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.delivery')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.gender')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.img')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category_type')),
            ],
        ),
    ]
