# Generated by Django 3.1 on 2022-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
