# Generated by Django 3.1 on 2022-06-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20220621_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toys',
            old_name='type',
            new_name='toys_type',
        ),
    ]
