# Generated by Django 3.1 on 2022-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20220621_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='from_category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='to_category',
            field=models.IntegerField(),
        ),
    ]
