# Generated by Django 4.0.5 on 2022-06-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_rename_type_worker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('img', models.ImageField(upload_to='static/images')),
                ('chegirma', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category')),
            ],
        ),
        migrations.CreateModel(
            name='Aksiya_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='type',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='aksiya',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.aksiya_code'),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.delivery'),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.gender'),
        ),
        migrations.AddField(
            model_name='aksiya',
            name='toys_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category_type'),
        ),
    ]
