# Generated by Django 4.0.5 on 2022-06-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_aksiya_aksiya_code_remove_worker_type_delete_market_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker_Type',
        ),
    ]
