# Generated by Django 4.0.5 on 2022-07-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0011_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksiya',
            name='chegirma',
        ),
    ]
