# Generated by Django 4.0.5 on 2022-07-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0013_remove_company_country_company_region_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
