# Generated by Django 4.0.5 on 2022-07-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0015_toys_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='aksiya',
            name='brend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toys.brend'),
            preserve_default=False,
        ),
    ]
